added verify job

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -60,10 +60,18 @@ jobs:
       - name: Deploy to DigitalOcean
         uses: digitalocean/action-doctl@v2
         with:
-          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
+          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
           command: |
-            doctl auth init -t "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"
+            doctl auth init -t "${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}"
             doctl compute ssh-key import my-key --public-key-file=$HOME/.ssh/id_rsa.pub
             doctl compute ssh-key list
             doctl compute droplet list
-            doctl compute droplet ssh ${{ secrets.DROPLET_IP_ADDRESS }} --ssh-command="git clone https://github.com/noveoko/24nme.github.io.git && cd <repository> && gunicorn app:app -b 0.0.0.0:80"
+            doctl compute droplet ssh ${{ secrets.SERVER_IP }} --ssh-command="git clone https://github.com/noveoko/24nme.github.io.git && cd <repository> && gunicorn main:app -b 0.0.0.0:80"
+             
+      - name: Verify app availability
+        run: |
+          set -e
+          if ! curl -Is https://24n.me | head -n 1 | grep "HTTP/1.[01] [23].."; then
+            echo "Error: App is not available"
+            exit 1
+          fi
